### ISSUE TITLE
Can't delete a collection

### ISSUE THREAD

**Issue by heesukim628** [MaayanLab/datacrossways_frontend#11]
Error deleting collections

<img width="431" alt="image" src="https://github.com/MaayanLab/datacrossways_frontend/assets/118917155/0c7bee26-183b-438f-bd0f-ceb2f931eefb">

**Comment by lachmann12** [comment]
fixed, but needs testing

**Comment by heesukim628** [comment]
It works now!

**Comment by lachmann12** [comment]
fixed
