### ISSUE TITLE
The term 'Lyme Commons' are still used

### ISSUE THREAD

**Issue by heesukim628** [MaayanLab/datacrossways_frontend#14]
<img width="1235" alt="Screenshot 2024-04-03 at 10 58 41 AM" src="https://github.com/MaayanLab/datacrossways_frontend/assets/118917155/16dfb91c-d69f-4c8a-ae02-98ecf1dcbff5">

**Comment by lachmann12** [comment]
the name is not final. Can still be decided and depends on the host server. Either is possible
