### ISSUE TITLE
Can't delete files from collection view

### ISSUE THREAD

**Issue by heesukim628** [MaayanLab/datacrossways_frontend#18]
When any of collection is selected (even it's unassigned), there's no 'delete files' but only 'remove from collection'

<img width="1017" alt="image" src="https://github.com/MaayanLab/datacrossways_frontend/assets/118917155/61312fc9-3f98-40d0-925e-992fe7aba472">

we can delete files only from https://lymecloud.org/myfiles

**Comment by lachmann12** [comment]
this is currently by design. I can revisit if it is too confusing.
