### ISSUE TITLE
Navbar on landing page changes when logged in

### ISSUE THREAD

**Issue by heesukim628** [MaayanLab/datacrossways_frontend#19]
before log in 
<img width="1512" alt="image" src="https://github.com/MaayanLab/datacrossways_frontend/assets/118917155/43debf7c-d81f-4038-bee0-c937b327f5fa">

after login - I guess this is only for the search and myfiles page?
<img width="896" alt="image" src="https://github.com/MaayanLab/datacrossways_frontend/assets/118917155/2a8b1262-49e6-4223-927f-fa11cdf37380">
<img width="1066" alt="image" src="https://github.com/MaayanLab/datacrossways_frontend/assets/118917155/900f6438-0d3c-436f-a83d-ddd56ad10b9f">

**Comment by lachmann12** [comment]
fixed
