### ISSUE TITLE
I was able to create a collection, but was not able to upload files, buttons in the edit are grayed out

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/datacrossways_frontend#6]
<img width="537" alt="Screen Shot 2023-11-11 at 9 36 11 PM" src="https://github.com/MaayanLab/datacrossways_frontend/assets/12749033/ec94f607-94fa-4ca0-8fd2-4612582061c3">

**Comment by lachmann12** [comment]
Files are all uploaded into a private collection. They then need to be moved into a destination folder. There is no simple way to make the upload go directly into a destination folder. Either the file can be moved by editing the file or once a file was uploaded the folder can be edited and files can be added.
