### ISSUE TITLE
After uploading a file it is not clear where you can upload/enter metadata/description

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/datacrossways_frontend#9]
The field says "null" and it is not editable
<img width="537" alt="Screen Shot 2023-11-11 at 9 42 47 PM" src="https://github.com/MaayanLab/datacrossways_frontend/assets/12749033/1a5c1a2d-b36e-40fd-a15d-92938d74615d">

**Comment by lachmann12** [comment]
files can be edited to add meta data: 
<img width="542" alt="image" src="https://github.com/MaayanLab/datacrossways_frontend/assets/32603869/9a9ab9b4-755f-4a9e-ace6-5833d5f0ec56">
